/**
 * Client-safe Puck config. Import this in "use client" components
 * (editors) instead of site.config.js to avoid pulling mongoose
 * into the browser bundle.
 *
 * AUTO-GENERATED by create-premast-site — do not edit manually.
 * Changes here will be overwritten on `npm run update`.
 */
import { baseBlocks, baseCategories } from "@/components/puck/puckConfig";
import { seoPlugin } from "@premast/site-plugin-seo";
import { uiPlugin } from "@premast/site-plugin-ui";
import { SeoScoreField, SearchIndexingField } from "@premast/site-plugin-seo/editor";
import { buildPuckConfig } from "@premast/site-core/puck";

const plugins = [seoPlugin(), uiPlugin()];

// Merge root fields from all plugins
const rootFields = {};
for (const plugin of plugins) {
  if (plugin.rootFields) Object.assign(rootFields, plugin.rootFields);
}

// Merge blocks from all plugins
const allBlocks = { ...baseBlocks };
for (const plugin of plugins) {
  if (plugin.blocks) Object.assign(allBlocks, plugin.blocks);
}

// Merge categories from all plugins
const allCategories = { ...baseCategories };
for (const plugin of plugins) {
  if (plugin.categories) Object.assign(allCategories, plugin.categories);
}

// Custom field overrides (client-side enhanced fields)
rootFields.noIndex = {
  type: "custom",
  label: "Search Indexing",
  render: SearchIndexingField,
};
rootFields.seoScore = {
  type: "custom",
  label: "SEO Score",
  render: SeoScoreField,
};

export const puckConfig = buildPuckConfig(allBlocks, allCategories, {}, rootFields);
